# Generated by Django 2.1.5 on 2019-02-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20190203_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='hitCounter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
