# Generated by Django 2.1.5 on 2019-03-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_professor_rmplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
