# Generated by Django 2.1.5 on 2019-03-16 01:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 16, 1, 21, 3, 6914, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
