# Generated by Django 2.1.5 on 2019-03-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0009_auto_20190318_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ManyToManyField(to='reviewer.Professor')),
            ],
        ),
    ]
