# Generated by Django 2.1.5 on 2019-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0011_auto_20190415_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text_hash',
            field=models.CharField(max_length=53),
        ),
    ]
