# Generated by Django 2.1.5 on 2019-04-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0012_auto_20190415_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.CharField(default='Default University', max_length=100),
            preserve_default=False,
        ),
    ]
