# Generated by Django 2.1.5 on 2019-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0013_professor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default='Neutral', max_length=20),
            preserve_default=False,
        ),
    ]
