# Generated by Django 2.1.5 on 2019-05-04 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0014_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ULoopReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.IntegerField()),
                ('helpfulness', models.IntegerField()),
                ('clarity', models.IntegerField()),
                ('easiness', models.IntegerField()),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Review')),
            ],
        ),
    ]
