# Generated by Django 2.1.5 on 2019-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0016_auto_20190505_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subreddit', models.CharField(max_length=50)),
            ],
        ),
    ]
