# Generated by Django 2.1.5 on 2019-05-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0018_auto_20190511_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='rating_pages',
        ),
        migrations.AddField(
            model_name='professor',
            name='rmp_snapshots',
            field=models.ManyToManyField(related_name='RateMyProfessor_Snapshots', to='reviewer.ReviewSnapshot'),
        ),
        migrations.AddField(
            model_name='professor',
            name='uloop_snapshots',
            field=models.ManyToManyField(related_name='uLoop_Snapshots', to='reviewer.ReviewSnapshot'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user_reviews',
            field=models.ManyToManyField(to='reviewer.Review'),
        ),
    ]
