# Generated by Django 2.1.5 on 2019-05-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0019_auto_20190512_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='uloop_snapshots',
        ),
    ]
