# Generated by Django 2.1.5 on 2019-05-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0020_remove_professor_uloop_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='uloop_snapshots',
            field=models.ManyToManyField(related_name='uLoop_Snapshots', to='reviewer.ReviewSnapshot'),
        ),
    ]
