# Generated by Django 2.1.5 on 2019-05-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0021_professor_uloop_snapshots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsnapshot',
            old_name='rmp_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='rmp_snapshots',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='uloop_snapshots',
        ),
        migrations.AddField(
            model_name='professor',
            name='rating_pages',
            field=models.ManyToManyField(to='reviewer.ReviewSnapshot'),
        ),
    ]
