# Generated by Django 2.1.5 on 2019-05-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0022_auto_20190512_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='rmp_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='school',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='professor',
            name='uloop_link',
            field=models.CharField(max_length=100),
        ),
    ]
